<a data-flickr-embed="true" href="https://www.flickr.com/photos/kirbyurner/52030543667/in/dateposted-public/" title="Zoom Background"><img src="https://live.staticflickr.com/65535/52030543667_1ec272fe0c_w.jpg" width="400" height="225" alt="Zoom Background"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

#### Showing...

About Broadcasting.

<a data-flickr-embed="true" href="https://www.flickr.com/photos/kirbyurner/52023352728/in/dateposted-public/" title="Broadcasting"><img src="https://live.staticflickr.com/65535/52023352728_a80a93ccba_z.jpg" width="640" height="485" alt="Broadcasting"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

In [ ]:
import numpy as np

In [2]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr2 = np.array([-1,0,1])

In [4]:
arr * arr2

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [5]:
vert_arr = np.array([3, 6, 9]).reshape(3,1)

In [6]:
vert_arr

array([[3],
       [6],
       [9]])

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr / vert_arr

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 0.83333333, 1.        ],
       [0.77777778, 0.88888889, 1.        ]])

 Official documentation: [np.around](https://numpy.org/doc/stable/reference/generated/numpy.around.html)

In [9]:
np.around(arr / vert_arr, 1)

array([[0.3, 0.7, 1. ],
       [0.7, 0.8, 1. ],
       [0.8, 0.9, 1. ]])

[Examples of rounding in numpy](https://pythonguides.com/python-numpy-round/)

In [21]:
np.round(arr / vert_arr, 2)

array([[0.33, 0.67, 1.  ],
       [0.67, 0.83, 1.  ],
       [0.78, 0.89, 1.  ]])

In [19]:
np.floor(arr / vert_arr)

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [10]:
np.array([1,2,3]) * np.array([1,2,3]).reshape(3,1)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [11]:
L = list(range(10))

In [13]:
L[:3] = 42, 42, 42

In [14]:
L

[42, 42, 42, 3, 4, 5, 6, 7, 8, 9]

In [15]:
M = np.array(range(10))
M

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
M[:3] = 42

In [17]:
M

array([42, 42, 42,  3,  4,  5,  6,  7,  8,  9])