<a data-flickr-embed="true" href="https://www.flickr.com/photos/kirbyurner/52030543667/in/dateposted-public/" title="Zoom Background"><img src="https://live.staticflickr.com/65535/52030543667_1ec272fe0c_w.jpg" width="400" height="225" alt="Zoom Background"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

#### Showing...

About numpy dtypes.

Official documentation:

* [numpy dtypes](https://numpy.org/doc/stable/reference/arrays.dtypes.html)

In [1]:
import numpy as np

In [11]:
np.sctypeDict

{'?': numpy.bool_,
 0: numpy.bool_,
 'byte': numpy.int8,
 'b': numpy.int8,
 1: numpy.int8,
 'ubyte': numpy.uint8,
 'B': numpy.uint8,
 2: numpy.uint8,
 'short': numpy.int16,
 'h': numpy.int16,
 3: numpy.int16,
 'ushort': numpy.uint16,
 'H': numpy.uint16,
 4: numpy.uint16,
 'i': numpy.int32,
 5: numpy.int32,
 'uint': numpy.uint64,
 'I': numpy.uint32,
 6: numpy.uint32,
 'intp': numpy.int64,
 'p': numpy.int64,
 7: numpy.int64,
 'uintp': numpy.uint64,
 'P': numpy.uint64,
 8: numpy.uint64,
 'long': numpy.int64,
 'l': numpy.int64,
 'L': numpy.uint64,
 'longlong': numpy.longlong,
 'q': numpy.longlong,
 9: numpy.longlong,
 'ulonglong': numpy.ulonglong,
 'Q': numpy.ulonglong,
 10: numpy.ulonglong,
 'half': numpy.float16,
 'e': numpy.float16,
 23: numpy.float16,
 'f': numpy.float32,
 11: numpy.float32,
 'double': numpy.float64,
 'd': numpy.float64,
 12: numpy.float64,
 'longdouble': numpy.float128,
 'g': numpy.float128,
 13: numpy.float128,
 'cfloat': numpy.complex128,
 'F': numpy.complex64,
 14:

The datatype below will be built using Void. Internally, the fields have names.

In [12]:
dt = np.dtype([('name', np.unicode_, 16), ('grades', np.float64, (2,))])

In [3]:
dt['name']

dtype('<U16')

In [4]:
dt['grades']

dtype(('<f8', (2,)))

In [13]:
x = np.array([('Sarah', (8.0, 7.0)), ('John', (6.0, 7.0))], dtype=dt)
x[1]

('John', [6., 7.])

In [14]:
x.dtype

dtype([('name', '<U16'), ('grades', '<f8', (2,))])

In [15]:
dt.kind

'V'

In [16]:
dt.char

'V'

In [17]:
dt.num

20

In [18]:
dt.str

'|V80'

In [19]:
dt.name

'void640'

In [20]:
dt.fields

mappingproxy({'name': (dtype('<U16'), 0),
              'grades': (dtype(('<f8', (2,))), 64)})

In [23]:
dt.descr

[('name', '<U16'), ('grades', '<f8', (2,))]

In [7]:
structured_type = np.dtype("i4, (2,3)f8, f4")

In [25]:
d = np.array([1,2,3,4,5,6],dtype='f8').reshape(2,3)
d

array([[1., 2., 3.],
       [4., 5., 6.]])

In [36]:
x = np.array(1, dtype=structured_type)
x

array((1, [[1., 1., 1.], [1., 1., 1.]], 1.),
      dtype=[('f0', '<i4'), ('f1', '<f8', (2, 3)), ('f2', '<f4')])

In [37]:
y = np.array(2, dtype=structured_type)
y

array((2, [[2., 2., 2.], [2., 2., 2.]], 2.),
      dtype=[('f0', '<i4'), ('f1', '<f8', (2, 3)), ('f2', '<f4')])

In [21]:
structured_dtype = np.dtype("a3, 3u8, (3,4)a10")

[vstack](https://www.w3resource.com/numpy/manipulation/vstack.php)

In [39]:
np.vstack((x,y))

array([[(1, [[1., 1., 1.], [1., 1., 1.]], 1.)],
       [(2, [[2., 2., 2.], [2., 2., 2.]], 2.)]],
      dtype=[('f0', '<i4'), ('f1', '<f8', (2, 3)), ('f2', '<f4')])

In [40]:
data = np.vstack((x,y))

In [41]:
data['f0']

array([[1],
       [2]], dtype=int32)

In [42]:
data['f1']

array([[[[1., 1., 1.],
         [1., 1., 1.]]],


       [[[2., 2., 2.],
         [2., 2., 2.]]]])