<a data-flickr-embed="true" href="https://www.flickr.com/photos/kirbyurner/52030543667/in/dateposted-public/" title="Zoom Background"><img src="https://live.staticflickr.com/65535/52030543667_1ec272fe0c_w.jpg" width="400" height="225" alt="Zoom Background"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

#### Showing...

The MaskedArray feature of numpy.

[Talk about MaskedArray type](https://numpy.org/doc/stable/reference/maskedarray.generic.html)

In [2]:
import numpy as np
np.__version__

'1.21.5'

In [4]:
ma = np.ma.array([1,2,3,4,5,6], mask=[1,0,0,0,0,1])
ma

masked_array(data=[--, 2, 3, 4, 5, --],
             mask=[ True, False, False, False, False,  True],
       fill_value=999999)

In [5]:
ma.data

array([1, 2, 3, 4, 5, 6])

In [6]:
ma.mask

array([ True, False, False, False, False,  True])

In [7]:
np.sum(ma)

14

In [16]:
keep = np.random.randint(1, 10, (8, 8)).astype(np.float64)
keep

array([[7., 6., 4., 9., 5., 8., 7., 8.],
       [9., 2., 6., 8., 6., 7., 5., 3.],
       [3., 5., 4., 2., 5., 4., 7., 4.],
       [4., 1., 6., 5., 4., 5., 8., 8.],
       [1., 2., 2., 4., 3., 8., 1., 3.],
       [5., 9., 5., 4., 2., 2., 6., 5.],
       [4., 7., 2., 6., 5., 3., 4., 6.],
       [1., 1., 2., 9., 5., 1., 7., 7.]])

In [19]:
keep[[0, 3, 5, 7],[1, 2, 5, 7]] = np.NaN  # random missing values
keep

array([[ 7., nan,  4.,  9.,  5.,  8.,  7.,  8.],
       [ 9.,  2.,  6.,  8.,  6.,  7.,  5.,  3.],
       [ 3.,  5.,  4.,  2.,  5.,  4.,  7.,  4.],
       [ 4.,  1., nan,  5.,  4.,  5.,  8.,  8.],
       [ 1.,  2.,  2.,  4.,  3.,  8.,  1.,  3.],
       [ 5.,  9.,  5.,  4.,  2., nan,  6.,  5.],
       [ 4.,  7.,  2.,  6.,  5.,  3.,  4.,  6.],
       [ 1.,  1.,  2.,  9.,  5.,  1.,  7., nan]])

In [44]:
ma_matrix = np.ma.array(keep, mask = np.isnan(keep))  # mask the NaNs
ma_matrix

masked_array(
  data=[[7.0, --, 4.0, 9.0, 5.0, 8.0, 7.0, 8.0],
        [9.0, 2.0, 6.0, 8.0, 6.0, 7.0, 5.0, 3.0],
        [3.0, 5.0, 4.0, 2.0, 5.0, 4.0, 7.0, 4.0],
        [4.0, 1.0, --, 5.0, 4.0, 5.0, 8.0, 8.0],
        [1.0, 2.0, 2.0, 4.0, 3.0, 8.0, 1.0, 3.0],
        [5.0, 9.0, 5.0, 4.0, 2.0, --, 6.0, 5.0],
        [4.0, 7.0, 2.0, 6.0, 5.0, 3.0, 4.0, 6.0],
        [1.0, 1.0, 2.0, 9.0, 5.0, 1.0, 7.0, --]],
  mask=[[False,  True, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False,  True, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False,  True, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False,  True]],
  fill_value=1e+20)

In [30]:
ma_matrix.shape

(8, 8)

In [31]:
ma_matrix.data

array([[ 7., nan,  4.,  9.,  5.,  8.,  7.,  8.],
       [ 9.,  2.,  6.,  8.,  6.,  7.,  5.,  3.],
       [ 3.,  5.,  4.,  2.,  5.,  4.,  7.,  4.],
       [ 4.,  1., nan,  5.,  4.,  5.,  8.,  8.],
       [ 1.,  2.,  2.,  4.,  3.,  8.,  1.,  3.],
       [ 5.,  9.,  5.,  4.,  2., nan,  6.,  5.],
       [ 4.,  7.,  2.,  6.,  5.,  3.,  4.,  6.],
       [ 1.,  1.,  2.,  9.,  5.,  1.,  7., nan]])

In [32]:
ma_matrix.size

64

In [33]:
ma_matrix.count()

60

In [34]:
ma_matrix.mean()

4.766666666666667

In [35]:
ma_matrix.sum()/ma_matrix.count()

4.766666666666667

In [37]:
ma_matrix.data.sum()

nan

In [42]:
np.nansum(ma_matrix.data)

286.0

In [43]:
np.sum(ma_matrix)

286.0