<a data-flickr-embed="true" href="https://www.flickr.com/photos/kirbyurner/52030543667/in/dateposted-public/" title="Zoom Background"><img src="https://live.staticflickr.com/65535/52030543667_1ec272fe0c_w.jpg" width="400" height="225" alt="Zoom Background"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>

#### Showing...

About numpy linspace when start and/or stop arguments are arrays.

Official documentation:

* [numpy linspace](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [1]:
import numpy as np

In [2]:
ones = np.ones((5,5))
twos = np.ones((5,5)) * 2

In [3]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
twos

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [5]:
np.linspace(ones, twos, num=5)

array([[[1.  , 1.  , 1.  , 1.  , 1.  ],
        [1.  , 1.  , 1.  , 1.  , 1.  ],
        [1.  , 1.  , 1.  , 1.  , 1.  ],
        [1.  , 1.  , 1.  , 1.  , 1.  ],
        [1.  , 1.  , 1.  , 1.  , 1.  ]],

       [[1.25, 1.25, 1.25, 1.25, 1.25],
        [1.25, 1.25, 1.25, 1.25, 1.25],
        [1.25, 1.25, 1.25, 1.25, 1.25],
        [1.25, 1.25, 1.25, 1.25, 1.25],
        [1.25, 1.25, 1.25, 1.25, 1.25]],

       [[1.5 , 1.5 , 1.5 , 1.5 , 1.5 ],
        [1.5 , 1.5 , 1.5 , 1.5 , 1.5 ],
        [1.5 , 1.5 , 1.5 , 1.5 , 1.5 ],
        [1.5 , 1.5 , 1.5 , 1.5 , 1.5 ],
        [1.5 , 1.5 , 1.5 , 1.5 , 1.5 ]],

       [[1.75, 1.75, 1.75, 1.75, 1.75],
        [1.75, 1.75, 1.75, 1.75, 1.75],
        [1.75, 1.75, 1.75, 1.75, 1.75],
        [1.75, 1.75, 1.75, 1.75, 1.75],
        [1.75, 1.75, 1.75, 1.75, 1.75]],

       [[2.  , 2.  , 2.  , 2.  , 2.  ],
        [2.  , 2.  , 2.  , 2.  , 2.  ],
        [2.  , 2.  , 2.  , 2.  , 2.  ],
        [2.  , 2.  , 2.  , 2.  , 2.  ],
        [2.  , 2.  , 2.  , 2.  ,

In [6]:
np.linspace(1, np.array([2,2,2,2]).reshape(2,2), num = 5)

array([[[1.  , 1.  ],
        [1.  , 1.  ]],

       [[1.25, 1.25],
        [1.25, 1.25]],

       [[1.5 , 1.5 ],
        [1.5 , 1.5 ]],

       [[1.75, 1.75],
        [1.75, 1.75]],

       [[2.  , 2.  ],
        [2.  , 2.  ]]])

In [7]:
np.linspace(np.array([2,2,2,2]).reshape(2,2), 4, num = 5)

array([[[2. , 2. ],
        [2. , 2. ]],

       [[2.5, 2.5],
        [2.5, 2.5]],

       [[3. , 3. ],
        [3. , 3. ]],

       [[3.5, 3.5],
        [3.5, 3.5]],

       [[4. , 4. ],
        [4. , 4. ]]])